### ISSUE TITLE
Desktop view

### ISSUE THREAD

**Issue by shrenicshah** [AlphaNerds/OMDBSearch#1]
Hi there,

This is a really impressive app you have developed. I just wanted to know how do I run this app locally and what do I need to do to simply view in on a desktop browser

**Comment by AlphaNerd** [comment]
Thanks, I hoped someone would find it useful. You can also find it here: [https://market.ionic.io/starters/omdb-search](https://market.ionic.io/starters/omdb-search)

**Requirements:** 
- Node.js
- Ionic Framework

**Install/Setup**
1) clone the repo
2) cd into your directory (ie. `$ cd OMDbApp`)
3) install dependencies (ie. `$ sudo npm install`)
4) run in browser (ie. `$ionic serve`)

If you want to build it out to a Mobile App, you will also need:
1) For iPhone dev: XCode -SDK
2) For Android: Android Studio - SDK

**Comment by shrenicshah** [comment]
Many thanks for that. I will give it go. Once again, great job!!
